use crate::bundle::{
    BUILTIN_CLOUDFLARE_WORKERS, BUILTIN_NODE_ASSERT, BUILTIN_NODE_ASYNC_HOOKS, BUILTIN_NODE_BUFFER,
    BUILTIN_NODE_CONSOLE, BUILTIN_NODE_CRYPTO, BUILTIN_NODE_DIAGNOSTICS_CHANNEL, BUILTIN_NODE_DNS,
    BUILTIN_NODE_DNS_PROMISES, BUILTIN_NODE_EVENTS, BUILTIN_NODE_FS, BUILTIN_NODE_FS_PROMISES,
    BUILTIN_NODE_HTTP, BUILTIN_NODE_HTTPS, BUILTIN_NODE_MODULE, BUILTIN_NODE_NET, BUILTIN_NODE_OS,
    BUILTIN_NODE_PATH, BUILTIN_NODE_PERF_HOOKS, BUILTIN_NODE_PROCESS, BUILTIN_NODE_PUNYCODE,
    BUILTIN_NODE_QUERYSTRING, BUILTIN_NODE_STREAM, BUILTIN_NODE_STREAM_CONSUMERS,
    BUILTIN_NODE_STREAM_PROMISES, BUILTIN_NODE_STREAM_WEB, BUILTIN_NODE_STRING_DECODER,
    BUILTIN_NODE_TEST, BUILTIN_NODE_TIMERS, BUILTIN_NODE_TIMERS_PROMISES, BUILTIN_NODE_TLS,
    BUILTIN_NODE_URL, BUILTIN_NODE_UTIL, BUILTIN_NODE_ZLIB,
};
mod assert;
mod r#async;
mod buffer;
mod crypto;
mod diagnostic;
mod event;
mod http;
mod module;
mod path;
mod punycode;
mod small;
mod stream;
mod system;
mod timer;
mod url;
mod util;
mod worker;
mod zlib;

use assert::NODE_ASSERT_SOURCE;
use r#async::NODE_ASYNC_HOOKS_SOURCE;
use buffer::NODE_BUFFER_SOURCE;
use crypto::NODE_CRYPTO_SOURCE;
use diagnostic::NODE_DIAGNOSTICS_CHANNEL_SOURCE;
use event::NODE_EVENTS_SOURCE;
use http::NODE_HTTP_SOURCE;
use module::NODE_MODULE_SOURCE;
use path::NODE_PATH_SOURCE;
use punycode::NODE_PUNYCODE_SOURCE;
use small::{
    NODE_CONSOLE_SOURCE, NODE_QUERYSTRING_SOURCE, NODE_STRING_DECODER_SOURCE,
    NODE_UNSUPPORTED_SOURCE,
};
use stream::{
    NODE_STREAM_CONSUMERS_SOURCE, NODE_STREAM_PROMISES_SOURCE, NODE_STREAM_SOURCE,
    NODE_STREAM_WEB_SOURCE,
};
use system::{NODE_OS_SOURCE, NODE_PERF_HOOKS_SOURCE, NODE_PROCESS_SOURCE};
use timer::{NODE_TIMERS_PROMISES_SOURCE, NODE_TIMERS_SOURCE};
use url::NODE_URL_SOURCE;
use util::NODE_UTIL_SOURCE;
use worker::CLOUDFLARE_WORKERS_SOURCE;
use zlib::NODE_ZLIB_SOURCE;

pub(crate) fn source(specifier: &str) -> Option<&'static str> {
    match specifier {
        BUILTIN_CLOUDFLARE_WORKERS => Some(CLOUDFLARE_WORKERS_SOURCE),
        BUILTIN_NODE_ASSERT => Some(NODE_ASSERT_SOURCE),
        BUILTIN_NODE_ASYNC_HOOKS => Some(NODE_ASYNC_HOOKS_SOURCE),
        BUILTIN_NODE_BUFFER => Some(NODE_BUFFER_SOURCE),
        BUILTIN_NODE_CONSOLE => Some(NODE_CONSOLE_SOURCE),
        BUILTIN_NODE_CRYPTO => Some(NODE_CRYPTO_SOURCE),
        BUILTIN_NODE_DIAGNOSTICS_CHANNEL => Some(NODE_DIAGNOSTICS_CHANNEL_SOURCE),
        BUILTIN_NODE_EVENTS => Some(NODE_EVENTS_SOURCE),
        BUILTIN_NODE_HTTP | BUILTIN_NODE_HTTPS => Some(NODE_HTTP_SOURCE),
        BUILTIN_NODE_MODULE => Some(NODE_MODULE_SOURCE),
        BUILTIN_NODE_OS => Some(NODE_OS_SOURCE),
        BUILTIN_NODE_PATH => Some(NODE_PATH_SOURCE),
        BUILTIN_NODE_PUNYCODE => Some(NODE_PUNYCODE_SOURCE),
        BUILTIN_NODE_PERF_HOOKS => Some(NODE_PERF_HOOKS_SOURCE),
        BUILTIN_NODE_PROCESS => Some(NODE_PROCESS_SOURCE),
        BUILTIN_NODE_QUERYSTRING => Some(NODE_QUERYSTRING_SOURCE),
        BUILTIN_NODE_STRING_DECODER => Some(NODE_STRING_DECODER_SOURCE),
        BUILTIN_NODE_STREAM => Some(NODE_STREAM_SOURCE),
        BUILTIN_NODE_STREAM_WEB => Some(NODE_STREAM_WEB_SOURCE),
        BUILTIN_NODE_STREAM_CONSUMERS => Some(NODE_STREAM_CONSUMERS_SOURCE),
        BUILTIN_NODE_STREAM_PROMISES => Some(NODE_STREAM_PROMISES_SOURCE),
        BUILTIN_NODE_TIMERS => Some(NODE_TIMERS_SOURCE),
        BUILTIN_NODE_TIMERS_PROMISES => Some(NODE_TIMERS_PROMISES_SOURCE),
        BUILTIN_NODE_UTIL => Some(NODE_UTIL_SOURCE),
        BUILTIN_NODE_URL => Some(NODE_URL_SOURCE),
        BUILTIN_NODE_ZLIB => Some(NODE_ZLIB_SOURCE),
        BUILTIN_NODE_DNS
        | BUILTIN_NODE_DNS_PROMISES
        | BUILTIN_NODE_FS
        | BUILTIN_NODE_FS_PROMISES
        | BUILTIN_NODE_NET
        | BUILTIN_NODE_TEST
        | BUILTIN_NODE_TLS => Some(NODE_UNSUPPORTED_SOURCE),
        _ => None,
    }
}
