{{- if and .Values.secrets.create (not .Values.secrets.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "peren.runtimeSecretName" . }}
  labels:
    {{- include "peren.labels" . | nindent 4 }}
type: Opaque
stringData:
{{- range $name, $value := .Values.secrets.values }}
  {{ $name }}: {{ $value | quote }}
{{- end }}
{{- end }}
