[package]
name = "peren-replication"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
peren-primitives.workspace = true
peren-storage.workspace = true
thiserror.workspace = true

[lints]
workspace = true

[dev-dependencies]
tokio.workspace = true
