[node]
node_id = "00000000-0000-0000-0000-000000000124"
advertise_addr = "127.0.0.1:7124"
listen = "127.0.0.1:7124"

[bucket]
kind = "memory"

[mtls]
ca_cert_path = "certs/ca.pem"
leaf_cert_path = "certs/leaf-cert.pem"
leaf_key_path = "certs/leaf-key.pem"

[secrets_store]
api-token = "API_TOKEN"

[[services]]
name = "secrets"
worker_bundle_path = "examples/javascript/secrets/worker.js"
compatibility_date = "2026-01-01"

[services.secrets]
MESSAGE = "MESSAGE"

[services.secrets_store_refs]
API_TOKEN = "api-token"

[[sockets]]
name = "public"
listen = "127.0.0.1:8124"
service = "secrets"
