declare module "cloudflare:test" {
  export const env: import("./types.js").TestEnv;
  export const SELF: import("./types.js").Fetcher;
  export const caches: import("./types.js").CacheStorage;
  export function createExecutionContext(): import("./types.js").ExecutionContext;
  export function waitOnExecutionContext(ctx: import("./types.js").ExecutionContext): Promise<void>;
  export function getPerenTestServerUrl(): string;
  export function runDurableObjectAlarm(stub: import("./types.js").DurableObjectStub): Promise<boolean>;
  export function evictDurableObject(stub: import("./types.js").DurableObjectStub): Promise<boolean>;
  export function listDurableObjectIds(namespace: string | import("./types.js").DurableObjectNamespace): Promise<unknown>;
  export function runInDurableObject<T>(
    stub: import("./types.js").DurableObjectStub,
    callback: (instance: unknown, storage: import("./types.js").DurableObjectTestStorage) => T | Promise<T>,
  ): Promise<T>;
  export type ProviderMetadata = import("./types.js").ProviderMetadata;
  export type ProviderBacked = import("./types.js").ProviderBacked;
  export type KvListOptions = import("./types.js").KvListOptions;
  export type KvListResult = import("./types.js").KvListResult;
  export type KvGetOptions = import("./types.js").KvGetOptions;
  export type KvPutOptions = import("./types.js").KvPutOptions;
  export type KvCompareOptions = import("./types.js").KvCompareOptions;
  export type KvCompareResult = import("./types.js").KvCompareResult;
  export type CacheQueryOptions = import("./types.js").CacheQueryOptions;
  export type R2ObjectBody = import("./types.js").R2ObjectBody;
  export type R2PutOptions = import("./types.js").R2PutOptions;
  export type R2ObjectEntry = import("./types.js").R2ObjectEntry;
  export type R2ListResult = import("./types.js").R2ListResult;
  export type R2ListOptions = import("./types.js").R2ListOptions;
  export type D1PreparedStatement = import("./types.js").D1PreparedStatement;
  export type QueueSendOptions = import("./types.js").QueueSendOptions;
  export type QueueMessage = import("./types.js").QueueMessage;
  export type VectorRecord = import("./types.js").VectorRecord;
  export type VectorQueryOptions = import("./types.js").VectorQueryOptions;
  export type VectorMatch = import("./types.js").VectorMatch;
  export type VectorQueryResult = import("./types.js").VectorQueryResult;
  export type VectorMutationResult = import("./types.js").VectorMutationResult;
  export type RateLimiterRequest = import("./types.js").RateLimiterRequest;
  export type RateLimiterResult = import("./types.js").RateLimiterResult;
  export type ContainerExecResult = import("./types.js").ContainerExecResult;
  export type ContainerStatus = import("./types.js").ContainerStatus;
  export type ContainerInstance = import("./types.js").ContainerInstance;
  export type AiBinding = import("./types.js").AiBinding;
  export type AiEmbeddingResult = import("./types.js").AiEmbeddingResult;
  export type AiTextResult = import("./types.js").AiTextResult;
  export type AnalyticsEngineDataset = import("./types.js").AnalyticsEngineDataset;
  export type Cache = import("./types.js").Cache;
  export type CacheStorage = import("./types.js").CacheStorage;
  export type ContainerBinding = import("./types.js").ContainerBinding;
  export type D1Database = import("./types.js").D1Database;
  export type DispatchNamespaceBinding = import("./types.js").DispatchNamespaceBinding;
  export type PerenWebSocket = import("./types.js").PerenWebSocket;
  export type WebSocketRequestResponsePair = import("./types.js").WebSocketRequestResponsePair;
  export type WebSocketRequestResponsePairConstructor = import("./types.js").WebSocketRequestResponsePairConstructor;
  export type DurableObjectState = import("./types.js").DurableObjectState;
  export type DurableObjectStateConstructor = import("./types.js").DurableObjectStateConstructor;
  export type DurableObjectId = import("./types.js").DurableObjectId;
  export type DurableObjectNamespace = import("./types.js").DurableObjectNamespace;
  export type DurableObjectStub = import("./types.js").DurableObjectStub;
  export type DurableObjectTestStorage = import("./types.js").DurableObjectTestStorage;
  export type ExecutionContext = import("./types.js").ExecutionContext;
  export type Fetcher = import("./types.js").Fetcher;
  export type HyperdriveBinding = import("./types.js").HyperdriveBinding;
  export type ImagesBinding = import("./types.js").ImagesBinding;
  export type KvNamespace = import("./types.js").KvNamespace;
  export type LoaderBinding = import("./types.js").LoaderBinding;
  export type OutboundBinding = import("./types.js").OutboundBinding;
  export type Queue = import("./types.js").Queue;
  export type QueueBatch<T = unknown> = import("./types.js").QueueBatch<T>;
  export type QueueBatchMessage<T = unknown> = import("./types.js").QueueBatchMessage<T>;
  export type QueueBatchMetrics = import("./types.js").QueueBatchMetrics;
  export type QueueRetryOptions = import("./types.js").QueueRetryOptions;
  export type R2Bucket = import("./types.js").R2Bucket;
  export type RateLimiterBinding = import("./types.js").RateLimiterBinding;
  export type ServiceBinding = import("./types.js").ServiceBinding;
  export type TestBinding = import("./types.js").TestBinding;
  export type TestEnv = import("./types.js").TestEnv;
  export type VectorizeIndex = import("./types.js").VectorizeIndex;
  export type WorkflowBinding = import("./types.js").WorkflowBinding;
  export type WorkflowInstance = import("./types.js").WorkflowInstance;
}

declare module "peren:test" {
  export const env: import("./types.js").TestEnv;
  export const SELF: import("./types.js").Fetcher;
  export const caches: import("./types.js").CacheStorage;
  export function createExecutionContext(): import("./types.js").ExecutionContext;
  export function waitOnExecutionContext(ctx: import("./types.js").ExecutionContext): Promise<void>;
  export function getPerenTestServerUrl(): string;
  export function runDurableObjectAlarm(stub: import("./types.js").DurableObjectStub): Promise<boolean>;
  export function evictDurableObject(stub: import("./types.js").DurableObjectStub): Promise<boolean>;
  export function listDurableObjectIds(namespace: string | import("./types.js").DurableObjectNamespace): Promise<unknown>;
  export function runInDurableObject<T>(
    stub: import("./types.js").DurableObjectStub,
    callback: (instance: unknown, storage: import("./types.js").DurableObjectTestStorage) => T | Promise<T>,
  ): Promise<T>;
  export type ProviderMetadata = import("./types.js").ProviderMetadata;
  export type ProviderBacked = import("./types.js").ProviderBacked;
  export type KvListOptions = import("./types.js").KvListOptions;
  export type KvListResult = import("./types.js").KvListResult;
  export type KvGetOptions = import("./types.js").KvGetOptions;
  export type KvPutOptions = import("./types.js").KvPutOptions;
  export type KvCompareOptions = import("./types.js").KvCompareOptions;
  export type KvCompareResult = import("./types.js").KvCompareResult;
  export type CacheQueryOptions = import("./types.js").CacheQueryOptions;
  export type R2ObjectBody = import("./types.js").R2ObjectBody;
  export type R2PutOptions = import("./types.js").R2PutOptions;
  export type R2ObjectEntry = import("./types.js").R2ObjectEntry;
  export type R2ListResult = import("./types.js").R2ListResult;
  export type R2ListOptions = import("./types.js").R2ListOptions;
  export type D1PreparedStatement = import("./types.js").D1PreparedStatement;
  export type QueueSendOptions = import("./types.js").QueueSendOptions;
  export type QueueMessage = import("./types.js").QueueMessage;
  export type VectorRecord = import("./types.js").VectorRecord;
  export type VectorQueryOptions = import("./types.js").VectorQueryOptions;
  export type VectorMatch = import("./types.js").VectorMatch;
  export type VectorQueryResult = import("./types.js").VectorQueryResult;
  export type VectorMutationResult = import("./types.js").VectorMutationResult;
  export type RateLimiterRequest = import("./types.js").RateLimiterRequest;
  export type RateLimiterResult = import("./types.js").RateLimiterResult;
  export type ContainerExecResult = import("./types.js").ContainerExecResult;
  export type ContainerStatus = import("./types.js").ContainerStatus;
  export type ContainerInstance = import("./types.js").ContainerInstance;
  export type AiBinding = import("./types.js").AiBinding;
  export type AiEmbeddingResult = import("./types.js").AiEmbeddingResult;
  export type AiTextResult = import("./types.js").AiTextResult;
  export type AnalyticsEngineDataset = import("./types.js").AnalyticsEngineDataset;
  export type Cache = import("./types.js").Cache;
  export type CacheStorage = import("./types.js").CacheStorage;
  export type ContainerBinding = import("./types.js").ContainerBinding;
  export type D1Database = import("./types.js").D1Database;
  export type DispatchNamespaceBinding = import("./types.js").DispatchNamespaceBinding;
  export type PerenWebSocket = import("./types.js").PerenWebSocket;
  export type WebSocketRequestResponsePair = import("./types.js").WebSocketRequestResponsePair;
  export type WebSocketRequestResponsePairConstructor = import("./types.js").WebSocketRequestResponsePairConstructor;
  export type DurableObjectState = import("./types.js").DurableObjectState;
  export type DurableObjectStateConstructor = import("./types.js").DurableObjectStateConstructor;
  export type DurableObjectId = import("./types.js").DurableObjectId;
  export type DurableObjectNamespace = import("./types.js").DurableObjectNamespace;
  export type DurableObjectStub = import("./types.js").DurableObjectStub;
  export type DurableObjectTestStorage = import("./types.js").DurableObjectTestStorage;
  export type ExecutionContext = import("./types.js").ExecutionContext;
  export type Fetcher = import("./types.js").Fetcher;
  export type HyperdriveBinding = import("./types.js").HyperdriveBinding;
  export type ImagesBinding = import("./types.js").ImagesBinding;
  export type KvNamespace = import("./types.js").KvNamespace;
  export type LoaderBinding = import("./types.js").LoaderBinding;
  export type OutboundBinding = import("./types.js").OutboundBinding;
  export type Queue = import("./types.js").Queue;
  export type QueueBatch<T = unknown> = import("./types.js").QueueBatch<T>;
  export type QueueBatchMessage<T = unknown> = import("./types.js").QueueBatchMessage<T>;
  export type QueueBatchMetrics = import("./types.js").QueueBatchMetrics;
  export type QueueRetryOptions = import("./types.js").QueueRetryOptions;
  export type R2Bucket = import("./types.js").R2Bucket;
  export type RateLimiterBinding = import("./types.js").RateLimiterBinding;
  export type ServiceBinding = import("./types.js").ServiceBinding;
  export type TestBinding = import("./types.js").TestBinding;
  export type TestEnv = import("./types.js").TestEnv;
  export type VectorizeIndex = import("./types.js").VectorizeIndex;
  export type WorkflowBinding = import("./types.js").WorkflowBinding;
  export type WorkflowInstance = import("./types.js").WorkflowInstance;
}
