[node]
node_id = "00000000-0000-0000-0000-000000000123"
advertise_addr = "127.0.0.1:7123"
listen = "127.0.0.1:7123"

[bucket]
kind = "memory"

[mtls]
ca_cert_path = "certs/ca.pem"
leaf_cert_path = "certs/leaf-cert.pem"
leaf_key_path = "certs/leaf-key.pem"

[[services]]
name = "api"
worker_bundle_path = "examples/javascript/rpc/worker.js"
compatibility_date = "2026-01-01"

[services.bindings.AUTH]
type = "service"
entrypoint = "auth"

[[services]]
name = "auth"
worker_bundle_path = "examples/javascript/rpc/auth.js"
compatibility_date = "2026-01-01"

[[sockets]]
name = "public"
listen = "127.0.0.1:8123"
service = "api"
